name: Trigger auto deployment for engagepub-container-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/engagepub-container-backend-AutoDeployTrigger-be6006e9-0db5-4e93-b894-7a93fc7263ac.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ENGAGEPUBCONTAINERBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ENGAGEPUBCONTAINERBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ENGAGEPUBCONTAINERBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.ENGAGEPUBCONTAINERBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ENGAGEPUBCONTAINERBACKEND_REGISTRY_PASSWORD }}
          containerAppName: engagepub-container-backend
          resourceGroup: Engagepub_group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


