name: Deploy to EC2
on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      # 1. Setup
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 2. Build Docker Image
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/engagepub-backend .

      # 3. Login to DockerHub
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 4. Push image to DockerHub
      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/engagepub-backend

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      # 1. Pull new docker image
      - name: docker pull
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/engagepub-backend

      # 2. Stop currently running container
      - name: docker stop container
        run: sudo docker stop $(sudo docker ps -q) 2>/dev/null || true

      # 3. Run new container with env variables injected
      - name: docker run new container
        run: |
          sudo docker run --name engagepub-prod --rm -d -p 80:5000 \
          -e DB_HOST=${{ secrets.DB_HOST }} \
          -e DB_NAME=${{ secrets.DB_NAME }} \
          -e DB_NAME=${{ secrets.DB_PASSWORD }} \
          -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
          ${{ secrets.DOCKERHUB_USERNAME }}/engagepub-backend

      # 4. Clean up old image
      - name: delete old docker image
        run: sudo docker system prune -f
