name: Deploy to EC2
on:
  push:
    branches: ["main", "dev"]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      # 1. Setup
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 2. Build Docker Image
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/engagepub-backend .

      # 3. Login to DockerHub
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 4. Push image to DockerHub
      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/engagepub-backend

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      # 1. Pull new docker image
      - name: docker pull
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/engagepub-backend

      # 2. Stop currently running container named engagepub-prod
      # - name: docker stop engagepub-prod container
      #  run: sudo docker stop engagepub-prod || true

      # 3. Remove existing container named engagepub-prod
      #- name: docker remove engagepub-prod container
      #  run: sudo docker rm engagepub-prod || true

      # 4. Run new container with env variables injected
      - name: docker run new container
        run: |
          sudo docker run --name engagepub-prod --rm -d -p 80:5000 \
          -e DB_HOST=${{ secrets.DB_HOST }} \
          -e DB_NAME=${{ secrets.DB_NAME }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
          -e COOKIE_SECRET=${{ secrets.COOKIE_SECRET }} \
          -e NODE_ENV=${{ secrets.NODE_ENV }} \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e AWS_REGION=${{ secrets.AWS_REGION }} \
          -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
          -e OPENAI_API_KEY \
          ${{ secrets.DOCKERHUB_USERNAME }}/engagepub-backend

      # 5. Clean up old image
      - name: delete old docker image
        run: sudo docker system prune -f
